### ISSUE TITLE
Forkerte HTTP status koder

### ISSUE THREAD

**Issue by sorenlouv** [dampfaergen/snapshotjs#1]
Jeg faldt over dette problem:

http://webcache.googleusercontent.com/search?q=cache:ICGzOjATF0QJ:www.kobstaden.dk/%3F_escaped_fragment_%3D/category/key/fashion+&cd=1&hl=en&ct=clnk&lr=lang_da%7Clang_en

Google indekserer normalt ikke 404 sider - men i vores tilfælde gør den, da vi returnerer Not Found sider med status kode 200.

Eksempel på side der bør returnere 404: 

```
curl -I http://snapshot.kobstaden.dk/?url_fragment=/category/key/fashion
```

**Comment by sorenlouv** [comment]
Nu er jeg træt af at se den her i min liste over åbne issues ;)

**Comment by laander** [comment]
Haha - hvad med at open source snapshotjs? Lille projekt, men måske nogen kan få gavn af det

**Comment by sorenlouv** [comment]
Repo'et er jo allerede public. Back in the day kunne vi godt have skrevet en blog post om det, men tror løbet er kørt. Google har (igen, igen) opdateret deres crawler, og det lader til, at den nu forstår selv avancerede SPAs.

**Comment by jakobholmelund** [comment]
Der er stadig facebook ;) men tror allerede nogen har lavet noget der
ligner rigtigt meget. Kan bare ikke lige huske hvad det hedder

**Comment by laander** [comment]
Ja, kan huske der var en SaaS service som gjorde præcis det. Gad vide hvor god Bing’s crawler er? (not that it matters much)

On May 18, 2015 at 2:07:44 PM, Jakob Holmelund (notifications@github.com) wrote:

Der er stadig facebook ;) men tror allerede nogen har lavet noget der
ligner rigtigt meget. Kan bare ikke lige huske hvad det hedder
